### ISSUE TITLE
Getting EXC_BAD_ACCESS after ~1 min

### ISSUE THREAD

**Issue by alex566** [Backendless/ios-SDK#11]
Hi. I have a problem with the latest version of the SDK. After about one minute of using application I get EXC_BAD_ACCESS with reason “-[BodyHolder body]: message sent to deallocated instance”. Stacktrace on screenshot (without NSZombie):
![screenshot 2016-07-03 00 40 07](https://cloud.githubusercontent.com/assets/7542506/16542576/c5b08548-40b6-11e6-8532-f5e4a16a184f.png)

**Comment by markpiller** [comment]
Please post to the support forum at http://support.backendless.com. Thanks!

**Comment by IsaAliev** [comment]
I have the same issue!

**Comment by markpiller** [comment]
@IsaAliev Please post to the support forum at http://support.backendless.com. Thanks!
