### ISSUE TITLE
OSX Support?

### ISSUE THREAD

**Issue by allanrojas** [Backendless/ios-SDK#110]
Hi,

I have to develop two apps, one in OSX and one in IOS, was planning on using Backendless for both, but the setup on OSX fails. I'm following [this guide](https://backendless.com/mobile-developers/quick-start-guide-for-ios/) for v3.x, and I installed v3.0.43 using cocoapods...

However, when I try to register an user on my OSX app, it crashes with this error:

> Server reported an error (ASYNC): Optional(FAULT = '2002' [Version is disabled or provided wrong application info (application id or secret key)] <Version is disabled or provided wrong application info (application id or secret key)>

The guide for iOS worked like a charm (using v4.0b), although it does a different thing (inserts an object in a table, instead of registering a new user).

Any ideas? I'm using the same APP ID and "iOS API KEY" for both apps, should I not?

**Comment by markpiller** [comment]
Please make sure to use the SDK built for OSX: https://cocoapods.org/pods/Backendless-osx-SDK

**Comment by allanrojas** [comment]
This is my podfile:
`target 'MelioraOSX' do
pod 'Backendless-osx-SDK'
end
`

And this is the code that crashes:
`    let backendless = Backendless.sharedInstance()!
        backendless.initApp(APPLICATION_ID, secret: API_KEY, version: VERSION_NUM)
        
        let user: BackendlessUser = BackendlessUser()
        user.email = "some.email@gmail.com"
        user.password = "password"
        
        backendless.userService.registering(user, response: { (_) -> () in
            print("User has been registered (ASYNC):")
        }, error: { ( fault ) -> () in
            print("Server reported an error (ASYNC): \(fault)")
        })
`

**Comment by markpiller** [comment]
is your app on the 3.x or 4.0 backend? (you can see the version in Backendless console, it will be right next to the logo)

**Comment by allanrojas** [comment]
4.0 backend :( is that why?

is there a way to set my backend to 3.x ? and if so, do I have to use the 3.x SDK for iOS as well?

**Comment by markpiller** [comment]
Yes, that's why. To switch to 3.x use the "arrows" icon next to the logo in Backendless Console. The SDK you're using is for 3.x.
