### ISSUE TITLE
Add permission parameter in loginWithFacebookSdk

### ISSUE THREAD

**Issue by taglia3** [Backendless/ios-SDK#13]
Is it possible to enforce additional permissions because the function does not seems to accept them.
The method is loginWithFacebookSdk. However the method easyLoginWithFacebookFieldsMapping does support permissions, but does not require the Facebook SDK.

In my app I don't want redirect with safari so I want to use directly the FB SDK.
A great enhancement will be add this parameter in loginWithFacebookSdk. My workaround now is to use directly the FB SDK and then create a new Backendless user.

**Comment by slavavdovichenko** [comment]
Please see this comment
<http://support.backendless.com/topic/login-with-facebook-issue#comment-20730>
.

On Thu, Aug 25, 2016 at 1:13 AM, Matteo Tagliafico <notifications@github.com

**Comment by taglia3** [comment]
Hi slavavdovichenko,
thanks for the response, but setting the read permission with the methods you've linked it's true only if I use the FBSDKLoginButton. How to achieve the same result using a custom button?

This is my scenario:
- custom button
- user tap my custom button
- I call Backendless.sharedInstace().userService. loginWithFacebookSDK(...)
- In Login with Facebook I want to pass the permission Array plus the fieldMapping.  At this moment I'm able to pass only the fieldMapping dictionary.

**Comment by slavavdovichenko** [comment]
Hi Matteo,

We add  loginWithFacebookSDK(...)
<https://github.com/Backendless/ios-SDK/blob/master/SDK/ios/backendless/include/UserService.h#L53>
 methods
<https://github.com/Backendless/ios-SDK/blob/master/SDK/ios/backendless/include/UserService.h#L53>
with permissions. You could  update the latest Backendless SDK (pod 3.0.37
release)

Regards,
Slava

**Comment by slavavdovichenko** [comment]
You can try our "Login With Facebook SDK" sample project
<https://drive.google.com/file/d/0B3yyaWhA4ib0di1fVGEtVVo4M0k/view?usp=sharing>
with new method.

**Comment by taglia3** [comment]
Hi Slava,
this is what I was looking for!
Thanks for the help.

Regards,
Matteo
