### ISSUE TITLE
UIUserNotificationCategory is deprecated.

### ISSUE THREAD

**Issue by calebkleveter** [Backendless/ios-SDK#14]
I just thought that I would give a heads up that `UIUserNotificationCategory` is deprecated is iOS 10.

I got the warning from `MessagingService.h` on line 65.

**Comment by slavavdovichenko** [comment]
But it works!
We will fix this option when iOS 10 are released.

**Comment by picciano** [comment]
iOS 10 has been out for a while now. It would be nice to get rid of the warning.
Thanks!
