### ISSUE TITLE
HEADERS MAIL

### ISSUE THREAD

**Issue by CristianCardosoA** [Backendless/ios-SDK#180]
Hello, one question. Is possible to add headers on a email using this method  or other method **backendless.messaging sendHTMLEmail**

Because we noticed that by default you are missing some important headers at the moment that your SDK send an email.

1.1 | MIME_HTML_ONLY | BODY: Message only has text/html MIME parts
1.4 | MISSING_DATE | Missing Date: header
-0.0 | NO_RECEIVED | Informational: message has no Received headers

I hope you can help me. Thanks.

**Comment by ksv510** [comment]
Hey Cristian,

there is no way to add headers, we will consider how to add this feature

**Comment by CristianCardosoA** [comment]
Alright Thanks. 

So I will closed this Issue, and consider like a new feature.
