### ISSUE TITLE
Newer API updates pushed to Cocoapods?

### ISSUE THREAD

**Issue by chrishamant** [Backendless/ios-SDK#2]
Inferring from code here - there are quite a few updates/bugfixes that have yet to be released? Were you planning on releasing 2.0.9 through cocoapods? Latest version available through Cocoapods seems to be 2.0.2 = 

Is the recommendation to utilize source releases? or is Cocoapods a supported option?

**Comment by markpiller** [comment]
Hi Chris,

We recommend using the source releases. You can also get a copy of the build at: https://backendless.com/backend-as-a-service/downloads/

We'll update Cocoapods this week.

Regards,
Mark

**Comment by chrishamant** [comment]
thanks!

**Comment by slavavdovichenko** [comment]
Hi Chris,

You can use the latest release of Backendless SDK at CocoaPods - 2.0.13

Regards,
Slava
