### ISSUE TITLE
tvOS Support??

### ISSUE THREAD

**Issue by Sebacho-Barajas** [Backendless/ios-SDK#35]
hi I wanted to know if you're adding tvOS support any time soon ?

**Comment by RomanPodymov** [comment]
No, currently it is not supported http://support.backendless.com/topic/tvos-sdk, you need to wait.

**Comment by RomanPodymov** [comment]
Hello @Sebacho-Barajas 
Looks like Backendless/ios-SDK [supports tvOS](https://github.com/Backendless/ios-SDK/blob/master/Pods/Backendless.podspec), you can close the issue.
