### ISSUE TITLE
Installing BackendLess via CocoaPods generates multiple build errors

### ISSUE THREAD

**Issue by robmontesinos** [Backendless/ios-SDK#4]
I am replacing Parse with BackendLess (ObjectiveC) on an iPhone app and when I install it via CocoaPods, I get 10 "no member named 'xxx' in the global namespace" errors in another library (AsyncDisplayKit) which is also using C++ functions.

I am using Xcode 7.2 building for iOS 9.2. When I remove Backendless-ios-SDK from the Podfile and run 'pod install' again, all the errors disappear and all is well. Is there something that I can do without rewriting C++ code? Thank you

**Comment by slavavdovichenko** [comment]
Hi,
Can you make a screenshot with these errors and attach it here?

**Comment by robmontesinos** [comment]
Thank you @slavavdovichenko - by the way, this library takes a looong time to install via CocoaPods.
![screen shot 2016-02-01 at 12 45 10 pm](https://cloud.githubusercontent.com/assets/258556/12730683/e63f53b8-c8e1-11e5-9ea9-24b3b776795c.png)

**Comment by robmontesinos** [comment]
Another screenshot
![screen shot 2016-02-01 at 12 47 29 pm](https://cloud.githubusercontent.com/assets/258556/12730734/2107fec8-c8e2-11e5-96fe-0dd3e63ca349.png)

**Comment by slavavdovichenko** [comment]
Please, attach your Podfile here

**Comment by slavavdovichenko** [comment]
Or give me your project - I investigate the issue. My email: slavav@themidnightcoders.com

**Comment by robmontesinos** [comment]
Thank you @slavavdovichenko - I just emailed you the Podfile

**Comment by slavavdovichenko** [comment]
Ok, I've reproduced this issue.

Here https://drive.google.com/file/d/0B3yyaWhA4ib0M0FULU5VZG56Vms/view?usp=sharing is the project with AsyncDisplayKit & Backendless-ios-SDK from CocoaPods, and build errors exist.

Here https://drive.google.com/file/d/0B3yyaWhA4ib0TGNtYUZOM0pnOVk/view?usp=sharing is the project with AsyncDisplayKit  from CocoaPods, and Backendless-ios-SDK is been added manually as this guide describes: https://backendless.com/mobile-developers/quick-start-guide-for-ios/, and built errors are absent.

So, you can configure your project by the second way.

Regards,
Slava

**Comment by robmontesinos** [comment]
Thank you Slava. I’ll have to do it the way you suggest. Is there a chance that this cocoa pods issue will be addressed soon?





Roberto Montesinos
robmontesinos@gmail.com
https://twitter.com/MontesinosRob
http://www.imdb.com/name/nm1090683/
http://resumes.actorsaccess.com/robertomontesinos
------------------------------------------------------

**Comment by slavavdovichenko** [comment]
The investigation of this problem requires a time - we let you know about the result asap.

**Comment by robmontesinos** [comment]
Thanks again @slavavdovichenko  - on a separate note, the lib folder is 206 MB - I plan on using BackendLess just for retrieving data from a few tables and push notifications. How would you suggest that I get the overall size of the app down?

**Comment by markpiller** [comment]
Hi Roberto, the linker pulls only the code/libs used in your app. The size of libs in the project doesn't reflect the size of the final app.

**Comment by robmontesinos** [comment]
Phew @markpiller - thank you very much. I'm looking forward to your parse migration seminar

**Comment by slavavdovichenko** [comment]
If you don't use the media service - the size will be small. Only if a binary code is used it will be added to app from the lib.

You can use these resources as examples:
https://backendless.com/blog-a-feature-a-day-challenge/
https://github.com/Backendless/iOS-Samples

**Comment by robmontesinos** [comment]
You're awesome Slava @slavavdovichenko !!

**Comment by slavavdovichenko** [comment]
Hi,
If you use CodoaPods to integrate Backendless in your project, and you get the problem with "time.t conflict", you should remove the file time.h from your project.
Choose  in your project Pod -> Pod -> Backendless-ios-SDK and push the "delete" key. Click "Move to Trash" button.
