### ISSUE TITLE
QueryOptions sortBy?

### ISSUE THREAD

**Issue by robmontesinos** [Backendless/ios-SDK#5]
I am currently implementing BackendLess and am having trouble as to how to sort a table by date descending.

I see the header for the QueryOptions class but it is not clear how to accomplish this typical request. Can you post some sample code? It would be greatly appreciated.

```ObjectiveC
#import <Foundation/Foundation.h>

@interface QueryOptions : NSObject <NSCopying>

@property (strong, nonatomic) NSNumber *pageSize;
@property (strong, nonatomic) NSNumber *offset;
@property (strong, nonatomic) NSArray *sortBy;
@property (strong, nonatomic) NSMutableArray *related;
@property (strong, nonatomic) NSNumber *relationsDepth;

-(id)initWithPageSize:(int)_pageSize offset:(int)_offset;
+(id)query;
+(id)query:(int)_pageSize offset:(int)_offset;

-(QueryOptions *)pageSize:(int)_pageSize;
-(QueryOptions *)offset:(int)_offset;
-(QueryOptions *)sortBy:(NSArray *)_sortBy;
-(QueryOptions *)related:(NSArray *)_related;
-(NSDictionary *)getQuery;
-(BOOL)addRelated:(NSString *)_related;
-(BOOL)isEqualToQuery:(QueryOptions *)query;
@end

**Comment by markpiller** [comment]
Use the sortBy property, when you add column name to sortBy do it in the following format:

"[column-name] DESC"

For example: "age DESC"

where "age" is the name of a column.

**Comment by robmontesinos** [comment]
Thank you @markpiller for such a quick reply. sortBy is an NSArray. Would this work?
```ObjectiveC
    QueryOptions *queryOption = [QueryOptions new];
    queryOption.sortBy = @[@"updated DESC"];
    
    BackendlessDataQuery *query = [BackendlessDataQuery query];
    query.whereClause = [NSString stringWithFormat:@"updated >= %@", updatedAt];
    query.queryOptions = queryOption;
    
    [backendless.persistenceService find:[BELMessages class] dataQuery:query response:^(BackendlessCollection *collection) {
        NSArray *results = [collection data];
        
    } error:^(Fault *fault) {
        NSLog(@"error updating results:: %@", fault);
    }];

**Comment by markpiller** [comment]
Roberto,

I apologize for misguiding you. When you add a column name to the sortBy array, it is going to be sorted in the descending order by default (meaning you just need to add property name):

`queryOption.sortBy = @[@"updated"];`

However, if you need it to be sorted in the ascending order, then you do it like this:

`queryOption.sortBy = @[@"updated ASC"];`

Hope this helps.

Regards,
Mark

**Comment by robmontesinos** [comment]
No worries Mark - thank you very much!!

**Comment by LiveRock** [comment]
I tried with SWIFT. No errors but it does not work. The data was not sorted according to my settings:

queryOptions.sortBy(["job_description ASC"])

has not effects whatsoever.

What am I doing wrong here?
