### ISSUE TITLE
CocoaPods install error

### ISSUE THREAD

**Issue by Robertoq7** [Backendless/ios-SDK#6]
Hi Backendless Team,

I wanna using the Backendless in my project so I added into pod file:

> pod 'Backendless-ios-SDK', '~>3.0.7'

but I got error:

> [!] Unable to satisfy the following requirements:
- `Backendless-ios-SDK (~> 3.0.0)` required by `Podfile`

I f I remove the version then the install will be success but the version just 2.0.11 and it's too old. I checked the cocoapods folder in the repository and the spodpec is exist for the 3.0.7 version:

https://github.com/Backendless/ios-SDK/blob/master/CocoaPods/Backendless-ios-SDK/3.0.7/Backendless-ios-SDK.podspec

What can be the problem?

Thank you,
Robert

**Comment by markpiller** [comment]
Hi Robert,

The instructions in the [doc](https://backendless.com/documentation/users/ios/users_requirements.htm), say:

Step 4 of the "Create Project with Cocoapods" section:

> Open your Podfile using your favorite text editor (or Xcode), and add a text that looks like this:

```
platform :ios, '8.0'
pod 'Backendless-ios-SDK', '~>3.0.0'
```

Where did you get 3.0.7 from?

**Comment by Robertoq7** [comment]
I tried first time the 3.0.0 but same error:

> [!] Unable to satisfy the following requirements:

- `Backendless-ios-SDK (~> 3.0.0)` required by `Podfile`

I hoped that maybe another, higher version will be work, that is why I tried the 3.0.7. I saw this version under  the git link what I sent.

**Comment by slavavdovichenko** [comment]
Hi Roberto,

I just created the new project using CocoaPods with the simple Podfile context (described in README):
pod 'Backendless-ios-SDK'
and it works fine for me (it does an user login to my test app), you can download this project - https://drive.google.com/open?id=0B3yyaWhA4ib0ZkUwclFVblhyNGc, try it and compare with yours.

Regards,
Slava

**Comment by slavavdovichenko** [comment]
Alternative way is to send your project you've created with CocoaPods - I'll investigate it
Mu email: slavav@themidnightcoders.com

**Comment by slavavdovichenko** [comment]
Maybe you should update your pod app? I really cannot reproduce this problem!

**Comment by Robertoq7** [comment]
Thank you very much yours help!  I reset the pod and after that the install worked

> pod repo remove master
pod setup

It was interesting problem because I could install other libraries.

**Comment by charbelhass** [comment]
git config --global ssh.postBuffer 523288000
git config --global http.postBuffer 523288000
Fixes this issue
