### ISSUE TITLE
Getting EXC_BAD_ACCESS code=1 on [fault message]

### ISSUE THREAD

**Issue by vibe0508** [Backendless/ios-SDK#7]
When I'm trying to access 'message' property of a Fault object, the EXC_BAD_ACCESS is raised. NSZoombie helped to figure out that [CFString retain] sent to deallocated instance

**Comment by slavavdovichenko** [comment]
Hi,
Backendless API sync methods can return Fault object (as exception, or by fault: **Fault method parameter). This 'fault' can be null - and  [fault message] will be cause of crash, because message is a property, not a method. When you got server response - you should check if fault != nil.

Here is an example (on swift, but sense is same) : 

   func saveNewContact() {
        
        let contact = Contact()
        contact.name = "Jack Daniels"
        contact.age = 147
        contact.phone = "777-777-777"
        contact.title = "Favorites"
        
        let dataStore = backendless.data.of(Contact.ofClass())
        
        // save object synchronously
        var error: Fault?
        let result = dataStore.save(contact, fault: &error) as? Contact
        if error == nil {
            print("Contact has been saved: \(result!.objectId)")
        }
        else {
            print("Server reported an error: \(error)")
        }
        
        // save object asynchronously
        dataStore.save(
            contact,
            response: { (result: AnyObject!) -> Void in
                let obj = result as! Contact
                print("Contact has been saved: \(obj.objectId)")
            },
            error: { (fault: Fault!) -> Void in
                print("fServer reported an error: \(fault)")
        })
  }

Regards,
Slava

**Comment by vibe0508** [comment]
Здравствуй тёзка,
In my case, the fault is actually not nil. And it's property 'message' is not nil. It has a link but a broken one. Please check if there is no 'weak' modifiers on this property.

Thanks

**Comment by slavavdovichenko** [comment]
Hi,

As you can see https://github.com/Backendless/ios-SDK/blob/master/SDK/lib/CommLibiOS/include/Responder.h
message property is 'assign'
but Fault object usually was created with static NSString's

Can you give me your code for investigation?

**Comment by spensko** [comment]
same here. if I'm trying to get 'message' from Fault object (not nil) in main queue

`[backendless.userService login:email password:password response:^(BackendlessUser *user){
    some completion code
    }error:^(Fault *error){
        NSString *msg = error.message; // OK
        dispatch_async(dispatch_get_main_queue(), ^{
            NSString *msg2 = error.message; // BAD_EXEC
        });
    }];`

**Comment by slavavdovichenko** [comment]
Fault object you are getting is 'autorelesed', so you have to save it anywhere before you invoke 'dispatch_async'

**Comment by Borisevich34** [comment]
Hi,
Can you help me please?
I got an exception in this code Swift 3.0:

```
let fault = Fault(message: "Message", detail: "Detail", faultCode: "Fault Code")
print(fault?.message)
```

Should I use a different constructor?

**Comment by markpiller** [comment]
@Borisevich34 what is the reason you're constructing a new instance of Fault?
