### ISSUE TITLE
SDK 4.x - macOS support?

### ISSUE THREAD

**Issue by edl00k** [Backendless/ios-SDK#89]
I've used Backendless for macOS application. Is make sense to expect the support macOS in the SDK 4.0? It would be great to get some advice on the future like just a wait [how long?] or migrate to REST API or find a new BaaS :) etc.

thanks

**Comment by markpiller** [comment]
We definitely plan to provide builds for MacOS as well tvOS. Currently, we're going through a massive cleanup of the library, as soon as it is done, we will move on to automating the process to create additional build targets.

**Comment by edl00k** [comment]
It's great!
thanks for quick reply
