### ISSUE TITLE
BackenlessCollection NextPage queryOptions are lost

### ISSUE THREAD

**Issue by ParadimeWeb** [Backendless/ios-SDK#9]
When calling the NextPage method from the BackendlessCollection class, the queryOptions are overwritten.

Example on line 172 of the BackendlessCollection.m file, you have:
`BackendlessDataQuery *dataQuery = [self.query copy];
            dataQuery.queryOptions = [QueryOptions query:(int)_pageSize offset:(int)_offset];
`
If I have setup a related array or a SortBy, these would be lost after you re-initialize the queryOptions object.

**Comment by markpiller** [comment]
Thank you for reporting this issue. We will get this resolved shortly.

**Comment by slavavdovichenko** [comment]
This issue is fixed,  you could update fixed libs from here (CommLibiOS & backendless).
